using Apm.Cli.Compilation;
using Apm.Cli.Primitives;
using AwesomeAssertions;
using FakeItEasy;

namespace Apm.Cli.Tests.Compilation;

public class TemplateBuilderTests
{
    // ── BuildConditionalSections ─────────────────────────────────────

    [Fact]
    public void BuildConditionalSections_EmptyInstructions_ReturnsEmpty()
    {
        var builder = A.Fake<ITemplateBuilder>();
        A.CallTo(() => builder.BuildConditionalSections(A<List<Instruction>>._)).Returns("");

        var result = builder.BuildConditionalSections([]);

        result.Should().BeEmpty();
    }

    [Fact]
    public void BuildConditionalSections_SingleInstruction_ReturnsContent()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var instructions = new List<Instruction>
        {
            new()
            {
                Name = "python-style",
                Description = "Python style",
                ApplyTo = "**/*.py",
                Content = "Use type hints"
            }
        };
        A.CallTo(() => builder.BuildConditionalSections(instructions))
            .Returns("## Files matching `**/*.py`\nUse type hints");

        var result = builder.BuildConditionalSections(instructions);

        result.Should().Contain("**/*.py");
        result.Should().Contain("Use type hints");
    }

    [Fact]
    public void BuildConditionalSections_MultipleInstructions_GroupsByPattern()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var instructions = new List<Instruction>
        {
            new() { Name = "py1", Description = "d", ApplyTo = "**/*.py", Content = "Python rule 1" },
            new() { Name = "py2", Description = "d", ApplyTo = "**/*.py", Content = "Python rule 2" },
            new() { Name = "ts1", Description = "d", ApplyTo = "**/*.ts", Content = "TypeScript rule" }
        };
        A.CallTo(() => builder.BuildConditionalSections(instructions))
            .Returns("## Files matching `**/*.py`\nPython rule 1\nPython rule 2\n\n## Files matching `**/*.ts`\nTypeScript rule");

        var result = builder.BuildConditionalSections(instructions);

        result.Should().Contain("**/*.py");
        result.Should().Contain("**/*.ts");
        result.Should().Contain("Python rule 1");
        result.Should().Contain("TypeScript rule");
    }

    // ── GenerateAgentsMdTemplate ─────────────────────────────────────

    [Fact]
    public void GenerateAgentsMdTemplate_EmptyData_ReturnsTemplate()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var data = new TemplateData { InstructionsContent = "", Version = "1.0.0" };
        A.CallTo(() => builder.GenerateAgentsMdTemplate(data)).Returns("# AGENTS.md\n\nGenerated by APM v1.0.0");

        var result = builder.GenerateAgentsMdTemplate(data);

        result.Should().Contain("AGENTS.md");
        result.Should().Contain("1.0.0");
    }

    [Fact]
    public void GenerateAgentsMdTemplate_WithInstructions_IncludesContent()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var data = new TemplateData
        {
            InstructionsContent = "## Files matching `**/*.py`\nUse type hints",
            Version = "0.7.0"
        };
        A.CallTo(() => builder.GenerateAgentsMdTemplate(data))
            .Returns("# AGENTS.md\n\n## Files matching `**/*.py`\nUse type hints\n\nGenerated by APM v0.7.0");

        var result = builder.GenerateAgentsMdTemplate(data);

        result.Should().Contain("Use type hints");
        result.Should().Contain("0.7.0");
    }

    [Fact]
    public void GenerateAgentsMdTemplate_WithChatmode_IncludesChatmodeContent()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var data = new TemplateData
        {
            InstructionsContent = "instructions here",
            Version = "1.0.0",
            ChatmodeContent = "You are an architect."
        };
        A.CallTo(() => builder.GenerateAgentsMdTemplate(data))
            .Returns("# AGENTS.md\n\ninstructions here\n\n# Chatmode\nYou are an architect.");

        var result = builder.GenerateAgentsMdTemplate(data);

        result.Should().Contain("You are an architect.");
    }

    [Fact]
    public void GenerateAgentsMdTemplate_WithoutChatmode_ExcludesChatmodeSection()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var data = new TemplateData
        {
            InstructionsContent = "instructions",
            Version = "1.0.0",
            ChatmodeContent = null
        };
        A.CallTo(() => builder.GenerateAgentsMdTemplate(data)).Returns("# AGENTS.md\n\ninstructions");

        var result = builder.GenerateAgentsMdTemplate(data);

        result.Should().NotContain("Chatmode");
    }

    // ── FindChatmodeByName ──────────────────────────────────────────

    [Fact]
    public void FindChatmodeByName_ExistingChatmode_Returns()
    {
        var builder = A.Fake<ITemplateBuilder>();
        var chatmodes = new List<Chatmode>
        {
            new() { Name = "architect", Description = "Architect mode", Content = "Arch content" },
            new() { Name = "reviewer", Description = "Review mode", Content = "Review content" }
        };
        A.CallTo(() => builder.FindChatmodeByName(chatmodes, "architect"))
            .Returns(chatmodes[0]);

        var result = builder.FindChatmodeByName(chatmodes, "architect");

        result.Should().NotBeNull();
        result!.Name.Should().Be("architect");
    }

    [Fact]
    public void FindChatmodeByName_NonExistent_ReturnsNull()
    {
        var builder = A.Fake<ITemplateBuilder>();
        A.CallTo(() => builder.FindChatmodeByName(A<List<Chatmode>>._, "missing"))
            .Returns(null);

        var result = builder.FindChatmodeByName([], "missing");

        result.Should().BeNull();
    }

    [Fact]
    public void FindChatmodeByName_EmptyList_ReturnsNull()
    {
        var builder = A.Fake<ITemplateBuilder>();
        A.CallTo(() => builder.FindChatmodeByName(A<List<Chatmode>>._, A<string>._))
            .Returns(null);

        var result = builder.FindChatmodeByName([], "anything");

        result.Should().BeNull();
    }
}

/// <summary>Stub implementation for testing — returns empty/null for all methods.</summary>
internal class StubTemplateBuilder : ITemplateBuilder
{
    public string BuildConditionalSections(List<Instruction> instructions) => "";
    public string GenerateAgentsMdTemplate(TemplateData data) => "";
    public Chatmode? FindChatmodeByName(List<Chatmode> chatmodes, string name) => null;
}

public class StubTemplateBuilderTests
{
    [Fact]
    public void BuildConditionalSections_ReturnsEmptyString()
    {
        ITemplateBuilder builder = new StubTemplateBuilder();

        var result = builder.BuildConditionalSections([]);

        result.Should().BeEmpty();
    }

    [Fact]
    public void GenerateAgentsMdTemplate_ReturnsEmptyString()
    {
        ITemplateBuilder builder = new StubTemplateBuilder();

        var result = builder.GenerateAgentsMdTemplate(new TemplateData());

        result.Should().BeEmpty();
    }

    [Fact]
    public void FindChatmodeByName_ReturnsNull()
    {
        ITemplateBuilder builder = new StubTemplateBuilder();

        var result = builder.FindChatmodeByName(
            [new Chatmode { Name = "test", Description = "d", Content = "c" }],
            "test");

        result.Should().BeNull();
    }
}

public class TemplateDataTests
{
    [Fact]
    public void DefaultValues_AreCorrect()
    {
        var data = new TemplateData();

        data.InstructionsContent.Should().BeEmpty();
        data.Version.Should().BeEmpty();
        data.ChatmodeContent.Should().BeNull();
    }

    [Fact]
    public void Properties_CanBeSet()
    {
        var data = new TemplateData
        {
            InstructionsContent = "instructions",
            Version = "1.2.3",
            ChatmodeContent = "chatmode"
        };

        data.InstructionsContent.Should().Be("instructions");
        data.Version.Should().Be("1.2.3");
        data.ChatmodeContent.Should().Be("chatmode");
    }
}

public class TemplateBuilderIntegrationTests : IDisposable
{
    private readonly string _tempDir;

    public TemplateBuilderIntegrationTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, true);
    }

    [Fact]
    public void Compiler_WithFakeBuilder_GeneratesExpectedOutput()
    {
        var builder = A.Fake<ITemplateBuilder>();
        A.CallTo(() => builder.BuildConditionalSections(A<List<Instruction>>._))
            .Returns("## Files matching `**/*.cs`\nFollow C# conventions");
        A.CallTo(() => builder.GenerateAgentsMdTemplate(A<TemplateData>._))
            .Returns("# AGENTS.md\n\n## Files matching `**/*.cs`\nFollow C# conventions");

        var compiler = new AgentsCompiler(_tempDir, templateBuilder: builder);
        var primitives = new PrimitiveCollection();
        primitives.AddPrimitive(new Instruction
        {
            Name = "csharp",
            Description = "C# conventions",
            ApplyTo = "**/*.cs",
            Content = "Follow C# conventions",
            Source = "local"
        });

        var config = new CompilationConfig { Strategy = "single-file", Target = "vscode", DryRun = true };
        var result = compiler.Compile(config, primitives);

        result.Success.Should().BeTrue();
        result.Content.Should().Contain("**/*.cs");
        result.Content.Should().Contain("Follow C# conventions");
    }

    [Fact]
    public void Compiler_WithMixedPrimitives_PassesOnlyInstructions()
    {
        var builder = A.Fake<ITemplateBuilder>();
        A.CallTo(() => builder.BuildConditionalSections(A<List<Instruction>>._)).Returns("");
        A.CallTo(() => builder.GenerateAgentsMdTemplate(A<TemplateData>._)).Returns("");

        var compiler = new AgentsCompiler(_tempDir, templateBuilder: builder);
        var primitives = new PrimitiveCollection();
        primitives.AddPrimitive(new Instruction
        {
            Name = "inst",
            Description = "d",
            ApplyTo = "**",
            Content = "c",
            Source = "local"
        });
        primitives.AddPrimitive(new Chatmode
        {
            Name = "chat",
            Description = "d",
            Content = "c",
            Source = "local"
        });
        primitives.AddPrimitive(new Context { Name = "ctx", Content = "c", Source = "local" });

        var config = new CompilationConfig { Strategy = "single-file", Target = "vscode", DryRun = true };
        compiler.Compile(config, primitives);

        A.CallTo(() => builder.BuildConditionalSections(
            A<List<Instruction>>.That.Matches(l => l.Count == 1)))
            .MustHaveHappenedOnceExactly();
    }
}
