using Apm.Cli.Primitives;
using Apm.Cli.Utils;

namespace Apm.Cli.Compilation;

/// <summary>Template building system for AGENTS.md compilation.</summary>
public class TemplateBuilder : ITemplateBuilder
{
    /// <summary>Build sections grouped by applyTo patterns.</summary>
    public string BuildConditionalSections(List<Instruction> instructions)
    {
        if (instructions.Count == 0)
            return "";

        var patternGroups = GroupInstructionsByPattern(instructions);
        var sections = new List<string>();

        foreach (var (pattern, patternInstructions) in patternGroups.OrderBy(kvp => kvp.Key))
        {
            sections.Add($"## Files matching `{pattern}`");
            sections.Add("");

            foreach (var instruction in patternInstructions)
            {
                var content = instruction.Content.Trim();
                if (string.IsNullOrEmpty(content))
                    continue;

                // Add source file comment
                string relativePath;
                try
                {
                    var cwd = Directory.GetCurrentDirectory();
                    relativePath = Path.IsPathRooted(instruction.FilePath)
                        ? Path.GetRelativePath(cwd, instruction.FilePath)
                        : instruction.FilePath;
                }
                catch
                {
                    relativePath = instruction.FilePath;
                }

                sections.Add($"<!-- Source: {relativePath} -->");
                sections.Add(content);
                sections.Add($"<!-- End source: {relativePath} -->");
                sections.Add("");
            }
        }

        return string.Join("\n", sections);
    }

    /// <summary>Generate the complete AGENTS.md file content.</summary>
    public string GenerateAgentsMdTemplate(TemplateData data)
    {
        var sections = new List<string>
        {
            "# AGENTS.md",
            "<!-- Generated by APM CLI from .apm/ primitives -->",
            CompilationConstants.BuildIdPlaceholder,
            $"<!-- APM Version: {data.Version} -->",
            ""
        };

        if (!string.IsNullOrEmpty(data.ChatmodeContent))
        {
            sections.Add(data.ChatmodeContent.Trim());
            sections.Add("");
        }

        if (!string.IsNullOrEmpty(data.InstructionsContent))
            sections.Add(data.InstructionsContent);

        sections.Add("---");
        sections.Add("*This file was generated by APM CLI. Do not edit manually.*");
        sections.Add("*To regenerate: `specify apm compile`*");
        sections.Add("");

        return string.Join("\n", sections);
    }

    /// <summary>Find a chatmode by name.</summary>
    public Chatmode? FindChatmodeByName(List<Chatmode> chatmodes, string name)
        => chatmodes.Find(c => c.Name == name);

    internal static Dictionary<string, List<Instruction>> GroupInstructionsByPattern(List<Instruction> instructions)
    {
        var groups = new Dictionary<string, List<Instruction>>();

        foreach (var instruction in instructions)
        {
            if (string.IsNullOrEmpty(instruction.ApplyTo))
                continue;

            if (!groups.TryGetValue(instruction.ApplyTo, out var list))
            {
                list = [];
                groups[instruction.ApplyTo] = list;
            }
            list.Add(instruction);
        }

        return groups;
    }
}
